<GraphCustom>:
    xmin: 0
    xmax: 599
    ymin: -1
    ymax: 1
    x_grid: True
    y_grid: True
    x_ticks_major: 200
    y_ticks_major: 1
    ylabel: 'Y'
    xlabel: 'Time (s)'
    y_grid_label: True
    x_grid_label: True
    padding: 5
    border_color: (0, 0, 0, 1.0)
    tick_color: (0.8, 0.8, 0.8, 1.0)
    background_color: (1, 1, 1, 1.0)
    label_options: {'color': (0, 0, 0, 1.0), 'bold': True}
